services:
  - type: web
    name: library-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: library-db
          property: hostname
      - key: DB_PORT
        fromDatabase:
          name: library-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: library-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: library-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: library-db
          property: password

databases:
  - name: library-db
    plan: free
    databaseName: library_db
