services:
  - type: web
    name: library-api
    env: java
    plan: free
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/*.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: library-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: library-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: library-db
          property: password

databases:
  - name: library-db
    plan: free
    databaseName: library_db
