spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

jwt.secret=supnum-library-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000
